name: Deploy API Docs

on:
  push:
    branches:
      - dev
    paths-ignore:
        - '**/README.md'

env:
  projectName: LibraryService

jobs:
  generate-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.*

      - name: Install dependencies
        run: dotnet restore
      
      - name: Install tools
        run: dotnet tool restore

      # See post build step in .csproj
      - name: Build dll
        run: | 
          dotnet build ${{ env.projectName }}.csproj -t:rebuild -verbosity:normal -property:Configuration=Release

      - name: Upload swagger.json
        uses: actions/upload-artifact@v4
        with:
          name: spec-file
          path: swagger.json

  deploy:
    needs: generate-openapi-spec
    runs-on: ubuntu-latest
    steps:
      - name: Download swagger.json
        uses: actions/download-artifact@v4
        with:
          name: spec-file

      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: swagger.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
